args:
  IOHKaccessKeyId:
    tag: NixStr
    contents: cardano-deployer
  CFaccessKeyId:
    tag: NixStr
    contents: cardano-deployer
  EmurgoaccessKeyId:
    tag: NixStr
    contents: cardano-deployer
topology: topology-mainnet-infra.yaml
environment: Production
installer-bucket: stub
nixpkgs: 31a956f18c9251064997085fd7732562b1854726
name: iohk-infra
files:
- deployments/keypairs.nix
- deployments/infrastructure.nix
- deployments/infrastructure-env-production.nix
- deployments/infrastructure-target-aws.nix
elements:
- Infra
target: AWS
