args:
  accessKeyId:
    tag: NixStr
    contents: cardano-deployer
environment: Production
name: iohk-infra
files:
- deployments/keypairs.nix
- deployments/infrastructure.nix
- deployments/infrastructure-env-production.nix
- deployments/infrastructure-target-aws.nix
elements:
- Infra
target: AWS
