steps:
  - label: 'iohk-ops'
    command: 'export NIX_PATH="nixpkgs=$(/run/current-system/sw/bin/nix-build "$(dirname -- $(readlink -f -- ${BASH_SOURCE[0]}))/fetch-nixpkgs.nix" -o nixpkgs)"; export NIX_BUILD_SHELL=/run/current-system/sw/bin/bash; /run/current-system/sw/bin/nix-shell -p nix -p bash -p coreutils --run scripts/ci.sh'
    agents:
      - "system=x86_64-linux"
    env:
      NIX_REMOTE: daemon
    agents:
      system: x86_64-linux
